language: generic

matrix:
  include:
    - os: linux
      sudo: false
      env: TEST_TYPE=js
      language: node_js
      node_js: '6'
      cache: 
        directories:
          - ./node_modules

    - os: linux
      sudo: false
      env: TEST_TYPE=android
      jdk: oraclejdk8
      language: android
      android:
        components:
          - tools
          - platform-tools
          - build-tools-23.0.1
          - android-23
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-android-support
      cache: 
        directories:
          - ./node_modules
          # cache .gradle for both gradle and gradle's cache
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_cache: rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

    - os: osx
      # We're using 7.2 currently, as xctool has issues with 7.3.
      # This also means that we're testing against iOS 9.2.
      osx_image: xcode7.2
      language: objective-c
      env: TEST_TYPE=ios
      cache:
        directories:
          - ./node_modules

# As seen in http://stackoverflow.com/a/31882307/2347774
# Prevent travis from building twice for PRs
branches:
  only:
    - master

install:
  - echo "Now testing $TEST_TYPE on $TRAVIS_OS_NAME"
  - echo "Using android emulator $EMULATOR"
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"

  # force node 6
  - nvm install 6
  - nvm use 6
  # turn off fancy npm stuff
  - npm config set spin=false
  - npm config set progress=false
  # install node deps
  - npm install

  ### do ios-only setup stuff
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" && "$TEST_TYPE" == "ios" ]]; then
      brew update
      brew install xctool;
    fi


script:
  # These sections will grow over time.
  # Each line is collapsed nicely in the travis output, which is why they're
  # grouped in this fashion.

  # JS-only tests - type checking and specs
  - if [[ "$TEST_TYPE" == "js" ]]; then npm run test; fi

  # iOS-only tests - building and specs
  - if [[ "$TEST_TYPE" == "ios" ]]; then npm run test:ios; fi

  # android-only tests - building and specs
  - if [[ "$TEST_TYPE" == "android" ]]; then npm run test:android; fi
